namespace HospitalMS.Business.Models;

public sealed record CreatePatientRequest(
    string MedicalRecordNumber,
    string FirstName,
    string LastName,
    DateTime DateOfBirth,
    string Email,
    string? PhoneNumber = null,
    string? Gender = null,
    string? BloodGroup = null,
    string? AddressLine1 = null,
    string? AddressLine2 = null,
    string? City = null,
    string? State = null,
    string? PostalCode = null,
    string? Country = null,
    string? EmergencyContactName = null,
    string? EmergencyContactPhone = null,
    string? EmergencyContactRelationship = null,
    string? EmergencyContactEmail = null,
    string? Allergies = null,
    string? ChronicConditions = null,
    string? Notes = null);

public sealed record UpdatePatientRequest(
    string FirstName,
    string LastName,
    DateTime DateOfBirth,
    string Email,
    string? PhoneNumber = null,
    string? Gender = null,
    string? BloodGroup = null,
    string? AddressLine1 = null,
    string? AddressLine2 = null,
    string? City = null,
    string? State = null,
    string? PostalCode = null,
    string? Country = null,
    string? EmergencyContactName = null,
    string? EmergencyContactPhone = null,
    string? EmergencyContactRelationship = null,
    string? EmergencyContactEmail = null,
    string? Allergies = null,
    string? ChronicConditions = null,
    string? Notes = null);

public sealed record PatientResponse(
    Guid Id,
    string MedicalRecordNumber,
    string FirstName,
    string LastName,
    DateTime DateOfBirth,
    string Email,
    string? PhoneNumber,
    string? Gender,
    string? BloodGroup,
    string? AddressLine1,
    string? AddressLine2,
    string? City,
    string? State,
    string? PostalCode,
    string? Country,
    string? EmergencyContactName,
    string? EmergencyContactPhone,
    string? EmergencyContactRelationship,
    string? EmergencyContactEmail,
    string? Allergies,
    string? ChronicConditions,
    string? Notes,
    DateTime CreatedAtUtc,
    DateTime? UpdatedAtUtc);
